### ISSUE TITLE
Tiler isn't working

### ISSUE THREAD

**Issue by NathanRSmith** [HackMichiana/otm-core#1]
I'm seeing 502 errors for tree layer on the main map. This leads me to thing that the tiler service isn't running correctly or Nginx isn't configured correctly.

**Comment by collinanderson** [comment]
/var/log/upstart/tiler.log says:

module.js:340
    throw err;
    ^
Error: Cannot find module '/usr/local/tiler/node_modules/windshaft/node_modules/grainstore/node_modules/millstone/node_modules/srs/lib/binding/node-v11-linux-x64/srs.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/tiler/node_modules/windshaft/node_modules/grainstore/node_modules/millstone/node_modules/srs/lib/srs.js:18:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by collinanderson** [comment]
It's installing a darwin binary instead of linux. no idea why. I opened this issue: https://github.com/mapbox/node-srs/issues/52

**Comment by NathanRSmith** [comment]
Weird... thanks for looking into it.

**Comment by collinanderson** [comment]
opened another issue here: https://github.com/OpenTreeMap/otm-tiler/issues/79

**Comment by collinanderson** [comment]
Ok, we figured out if we run `npm install --target-platform=linux --unsafe-perm` we can force the linux target, and we were able to get srs to build, and zipfile, but the same trick didn't work for mapnick. It tries to complie something, and eats up a bunch of memory and eventually gets killed by the kernel.

```
collin@treemap:/usr/local/tiler/node_modules/windshaft/node_modules/mapnik$ sudo npm install --target-platform=linux --unsafe-perm
npm WARN package.json mapnik@0.7.28 No license field.

> mapnik@0.7.28 install /usr/local/tiler/node_modules/windshaft/node_modules/mapnik
> node-gyp rebuild
 make: Entering directory `/usr/local/tiler/node_modules/windshaft/node_modules/mapnik/build'
CXX(target) Release/obj.target/_mapnik/src/node_mapnik.o
 g++: internal compiler error: Killed (program cc1plus)
 Please submit a full bug report,
 with preprocessed source if appropriate.
 See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
 make: *** [Release/obj.target/_mapnik/src/node_mapnik.o] Error 4
 make: Leaving directory `/usr/local/tiler/node_modules/windshaft/node_modules/mapnik/build'
 gyp ERR! build error
 gyp ERR! stack Error: `make` failed with exit code: 2
 gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
 gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
 gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
 gyp ERR! System Linux 3.13.0-32-generic
 gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
 gyp ERR! cwd /usr/local/tiler/node_modules/windshaft/node_modules/mapnik
 gyp ERR! node -v v0.10.37
 gyp ERR! node-gyp -v v2.0.1
 gyp ERR! not ok

 npm ERR! Linux 3.13.0-32-generic
 npm ERR! argv "node" "/usr/bin/npm" "install" "--target-platform=linux" "--unsafe-perm"
 npm ERR! node v0.10.37
 npm ERR! npm  v2.13.0
 npm ERR! code ELIFECYCLE
 npm ERR! mapnik@0.7.28 install: `node-gyp rebuild`
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the mapnik@0.7.28 install script 'node-gyp rebuild'.
 npm ERR! This is most likely a problem with the mapnik package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR!     node-gyp rebuild
 npm ERR! You can get their info via:
 npm ERR!     npm owner ls mapnik
 npm ERR! There is likely additional logging output above.

 npm ERR! Please include the following file with any support request:
 npm ERR!     /usr/local/tiler/node_modules/windshaft/node_modules/mapnik/npm-debug.log
```

**Comment by collinanderson** [comment]
Ok, I rebooted the server to clear the swap, then added 4G of swap following this article: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

And _now_ it's working correctly!

All of the linux platform issues went away when I did `sudo npm install` rather than `npm install` as root. No idea why (actually, the --verbose flag points to things being cached in my user folder, so maybe root's cache is messed up). Anyway, the tiler is up and running again for the first time in over 2 months. :)

**Comment by danrneumann** [comment]
Awesome!

**Comment by NathanRSmith** [comment]
Nice work!

**Comment by danrneumann** [comment]
Still appears to be broken. Anybody want to help dig in again?

**Comment by seansummers** [comment]
It's fixed, but we still haven't gone anywhere!
